allprojects {
    group = 'org.sitenetsoft'
    version = '1.0.0-SNAPSHOT'

    repositories {
        mavenCentral()
        mavenLocal()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'jacoco'

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }

    compileJava {
        options.encoding = 'UTF-8'
        options.compilerArgs << '-parameters'
    }

    compileTestJava {
        options.encoding = 'UTF-8'
    }

    jacoco {
        toolVersion = '0.8.14'
    }

    jacocoTestReport {
        reports {
            xml.required = true
            html.required = true
        }
    }

    test {
        finalizedBy jacocoTestReport
    }
}
