plugins {
    id 'io.quarkus.extension'
    // TusClient's public API exposes Vert.x, Mutiny-Vert.x and CDI types; consumers need them at
    // compile scope.
    id 'java-library'
}

quarkusExtension {
    deploymentModule = 'client-deployment'
    deploymentArtifact = "${project.group}:${rootProject.ext.publishedArtifactIds['client-deployment']}:${project.version}"
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    api 'io.quarkus:quarkus-arc'
    api 'io.quarkus:quarkus-vertx'
    api 'io.smallrye.reactive:smallrye-mutiny-vertx-core'

    annotationProcessor enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    annotationProcessor 'io.quarkus:quarkus-extension-processor'

    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

test {
    useJUnitPlatform()
}
