plugins {
    id 'java-library'
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-core-deployment'
    implementation 'io.quarkus:quarkus-arc-deployment'
    implementation 'io.quarkus:quarkus-rest-deployment'
    implementation 'io.quarkus:quarkus-scheduler-deployment'
    implementation 'io.quarkus:quarkus-vertx-deployment'
    implementation project(':runtime')
    implementation 'io.quarkus:quarkus-vertx-http-dev-ui-spi'

    annotationProcessor enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    annotationProcessor 'io.quarkus:quarkus-extension-processor'
}
