quarkus.tus.sse-enabled=true
quarkus.tus.auth-enabled=false
quarkus.tus.max-size=104857600
quarkus.tus.max-chunk-size=1024
quarkus.tus.expiration-hours=1
quarkus.tus.store.local.upload-dir=${java.io.tmpdir}/quarkus-tus-it-uploads
